name: Deploy to EC2 (PROD)

on:
    push:
        branches:
            - main

env:
    EC2_HOST: 13.232.20.173
    EC2_USERNAME: ubuntu
    PORT: 3003

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Prepare .env file
              run: |
                  echo "PORT=${{ env.PORT }}" >> .env
                  echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
                  echo "FB_APP_ID=${{ secrets.FB_APP_ID }}" >> .env
                  echo "FB_CONFIG_ID=${{ secrets.FB_CONFIG_ID }}" >> .env
                  echo "FB_PAGE_ID=${{ secrets.FB_PAGE_ID }}" >> .env
                  echo "INSTA_PAGE_ID=${{ secrets.INSTA_PAGE_ID }}" >> .env
                  echo "AWS_S3_ACCESS_KEY=${{ secrets.AWS_S3_ACCESS_KEY }}" >> .env
                  echo "AWS_S3_ACCESS_SECRET=${{ secrets.AWS_S3_ACCESS_SECRET }}" >> .env
                  echo "AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}" >> .env
                  echo "AWS_S3_REGION=${{ secrets.AWS_S3_REGION }}" >> .env
                  echo "AWS_S3_URL=${{ secrets.AWS_S3_URL }}" >> .env

            - name: Zip the project
              run: zip -r tk-instagram-publish.zip . -x "*.git*"

            - name: Create SSH key file from GitHub secret
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ env.EC2_HOST }} >> ~/.ssh/known_hosts

            - name: Copy ZIP file to EC2 instance
              run: scp -i ~/.ssh/id_rsa -o "StrictHostKeyChecking=no" tk-instagram-publish.zip ${{ env.EC2_USERNAME }}@${{ env.EC2_HOST }}:/var/www

            - name: SSH into EC2 and deploy
              run: |
                  ssh -i ~/.ssh/id_rsa -o "StrictHostKeyChecking=no" ${{ env.EC2_USERNAME }}@${{ env.EC2_HOST }} << 'ENDSSH'
                  cd /var/www
                  sudo rm -rf tk-instagram-publish
                  mkdir tk-instagram-publish
                  mv tk-instagram-publish.zip tk-instagram-publish
                  cd tk-instagram-publish
                  unzip tk-instagram-publish.zip
                  rm tk-instagram-publish.zip
                  sudo apt-get install ca-certificates fonts-liberation libasound2t64 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
                  sudo npm install
                  npm run build
                  pm2 start /var/www/tk-instagram-publish/ecosystem.config.cjs || pm2 restart tk-instagram-publish
                  pm2 save
                  ENDSSH
